[project]
name = "mcp-snippets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.23",
    "mcp[cli]>=1.6.0",
    "openai>=1.71.0",
    "pymilvus>=2.5.6",
]
